<html>
<head>
<title>Acme, Inc.</title>
<link rel="stylesheet" href="http://students.oreillyschool.com/resource/php_lesson.css" type="text/css" />
</head>
<body>
<div class="topbar">
ACME, INC.
</div>
<table>
<tr>
<td class="content">
<h3>Download our latest plugin</h3>
<p>If you have the right browser and machine combo:<br/>
Macintosh machines with the Firefox browser or Windows machines with the Internet Explorer browser or the Firefox browser<br/><br/>



</p>

</td></tr></table>


